# Generated by Django 5.0.2 on 2024-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_group_admins_remove_group_super_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo_couv',
            field=models.FileField(blank=True, null=True, upload_to='media/group/'),
        ),
        migrations.AddField(
            model_name='group',
            name='photo_grp',
            field=models.FileField(blank=True, null=True, upload_to='media/group/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster_photo',
            field=models.ImageField(default='poster.jpg', upload_to='media/posters/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to=''),
        ),
    ]
