# Generated by Django 5.0.2 on 2024-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group_photo_couv_group_photo_grp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='profile_pics/'),
        ),
    ]
